version: "3.4"

services:
  hz__postgres:
    image: postgres:10
    restart: "no"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - ./.data/pgsql/:/var/lib/postgresql/data
      - ./.docker/postgres-init.sql:/docker-entrypoint-initdb.d/init.sql
  hz_redis-stack:
    image: redis/redis-stack-server:latest
    restart: no
    ports:
      - 6379:6379
    volumes:
      - ./.data/redis:/data
