default-zone-id: "-"
bot:
  token: "-"
  name: "-"
  chat-id: "-"
  max-allowed-entity-size-bytes: 10_000_000 # 10mb
  poll_new_mails: false
  feedback:
    enabled: true
    sent-to-user-id: "-"
    thanks-for-feedback-message: Thanks for you feedback!
    give-feedback-message: Теперь напиши свой фидбек, пожалуйста, или нажми /cancel_feedback для отмены
google-cloud:
  calendar:
    api:
      key: "-"
calendar:
  calendar-id: "-"
mail:
  username: "-"
  password: "-"
  debug: false
  store_protocol: imaps
  imaps:
    host: "-"
    port: 993
    timeout: 10000
spring:
  datasource:
    url: ${DB_URL:jdbc:h2:mem:herrziggy;DATABASE_TO_UPPER=false;DB_CLOSE_DELAY=-1}
    username: ${DB_USERNAME:sa}
    password: ${DB_PASSWORD:}
    driverClassName: ${DB_DRIVER_CLASS_NAME:org.h2.Driver}
  jpa:
    open-in-view: false
    database-platform: ${DB_DATABASE_PLATFORM:org.hibernate.dialect.H2Dialect}
logging:
  level:
    root: warn
---
spring:
  config:
    activate:
      on-profile:
        - root-info
logging:
  level:
    root: info
---
spring:
  config:
    activate:
      on-profile:
        - app-debug
logging:
  level:
    root: warn
    me.jonua.herrziggy_bot: debug
---
spring:
  config:
    activate:
      on-profile:
        - app-trace
logging:
  level:
    root: warn
    me.jonua.herrziggy_bot: trace
