default-zone-id: "-"
bot:
  token: "-"
  chat-id: "-"
  max-allowed-entity-size-bytes: 10_000_000 # 10mb
mail:
  username: "-"
  password: "-"
  debug: false
  store_protocol: imaps
  imaps:
    host: "-"
    port: 993
    timeout: 10000
