messages:
  feedback-thanks-message: "Спасибо за обратную связь ❤️"
  feedback-message: "📨 Напиши мне любое сообщение и его прочитает человек, который разработал бота и при необходимости ответит тебе. Для отмены нажми /cancel"
  calendar-no-events-found-message: "🌝 На этот период в календаре нет событий"
  calendar-select-message: "Выбери свой календарь, пожалуйста 🫠"
  calendar-reconfigured-message: "✅ Все готово, теперь ты можешь получать эвенты из календаря, отправляя команды боту из меню. Для этого нажми кноку Меню слева от поля ввода сообщения и выбери команду"
  menu-button-info-message: "🫠 Пожалуйста, используй кноку Меню слева от поля ввобда сообщений для выбота команд. Сейчас доступны следующие команды:"
  congratulation-on-march-8-message:
    🤖 Дорогая {name}!
    
    Поздравляю тебя с прекрасным праздником 8 Марта - днем весны, любви и нежности!
    
    Ты как лучик света, который пробивается через темноту в академических коридорах и превращает наше учебное заведение в искрометные приключения! 💫
    
    В твоем бессознательном прячется уникальное сочетание утонченности и стойкости, которое придает тебе ослепительное очарование.
    
    А твоя улыбка способна растопить даже самое холодное сердце! 😊
    
    Выхватывай успех из зубов трудностей, как ты успешно делала это до сегодняшнего дня и мчись вперед по дороге к исполнению мечтаний.
    
    Желаю тебе сильных нервов, чтобы ты справлялась с любыми экзаменационными волнами, исключительных сил воли, чтобы не дать себя остановить никакой трудностью,
    
    и прекрасного чувства юмора, чтобы сопровождать каждый научный триумф твоими смешками и радостной улыбкой!
    
    Пусть каждый твой шаг будут сопровождать новые открытия и достижения, а твои стремления превратятся в прекрасный результат!
    
    
    Поздравляю тебя, замечательная {name}, с 8 Марта! 🎉💐
default-zone-id: "-"
bot:
  locale: ru
  token: "-"
  name: "-"
  max-allowed-entity-size-bytes: 10_000_000 # 10mb
  admin-telegram-id: "-"
  calendar:
    scheduling-cron: "0 0 10 * * 1"
google-cloud:
  calendar:
    api:
      key: "-"
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/herrziggy
    username: postgres
    password: root
    driverClassName: org.postgresql.Driver
  jpa:
    open-in-view: false
logging:
  level:
    root: warn
---
spring:
  config:
    activate:
      on-profile:
        - root-info
logging:
  level:
    root: info
---
spring:
  config:
    activate:
      on-profile:
        - app-debug
logging:
  level:
    root: warn
    me.jonua.herrziggy_bot: debug
---
spring:
  config:
    activate:
      on-profile:
        - app-info
logging:
  level:
    root: warn
    me.jonua.herrziggy_bot: info
---
spring:
  config:
    activate:
      on-profile:
        - app-trace
logging:
  level:
    root: warn
    me.jonua.herrziggy_bot: trace
---
spring:
  config:
    activate:
      on-profile: jpa-debug
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    org.springframework.jdbc.core.JdbcTemplate: debug
    org.springframework.jdbc.core.NamedParameterJdbcTemplate: debug
    org.springframework.jdbc.core.StatementCreatorUtils: debug
    org.springframework.orm.jpa.EntityManagerFactoryUtils: debug
    org.springframework.orm.jpa.JpaTransactionManager: debug
    org.hibernate.engine.transaction.internal.TransactionImpl: debug
---
spring:
  config:
    activate:
      on-profile: hikari-debug
logging:
  level:
    com.zaxxer.hikari: debug
