default-zone-id: "-"
bot:
  token: "-"
  chat-id: "-"
  max-allowed-entity-size-bytes: 10_000_000 # 10mb
mail:
  username: "-"
  password: "-"
  debug: false
  store_protocol: imaps
  imaps:
    host: "-"
    port: 993
    timeout: 10000
logging:
  level:
    root: warn
---
spring:
  config:
    activate:
      on-profile:
        - root-info
logging:
  level:
    root: info
---
spring:
  config:
    activate:
      on-profile:
        - app-debug
logging:
  level:
    root: warn
    me.jonua.herrziggy_bot: debug
